### ISSUE TITLE
Expose JsonTokenHelper in GitkitClient

### ISSUE THREAD

**Issue by jiangwei1221** [google/identity-toolkit-java-client#12]
Given a Gitkit token, I'd like to have a verified version of JSON object instead of just the GitkitUser. To do so I suggest to provide a getter for JsonTokenHelper. Please confirm this change is acceptable.

Thanks!

**Comment by liujin-google** [comment]
Returning the JSON object is a reasonable request. How about add a GitkitUser.getJson() method, or GitkitClient.validateTokenToJson()?

**Comment by jiangwei1221** [comment]
I'm interested in the expiry of the token so GitkitClient.validateTokenToJson() seems more reasonable. I'll create a pull request.
