### ISSUE TITLE
GitkitUser does not expose the email "verified" status

### ISSUE THREAD

**Issue by robert4os** [google/identity-toolkit-java-client#23]
Hi

 'Password-users' have their email not verified and we need to know this in our signin flow. However, GitkitUser does not expose the JSON value of "verified".

GitkitClient provides a validateTokenToJson which we can use to get to the information but for this we have to get the token value first and getting the token we have to read the cookie again.
JsonObject jsonToken = gitkitClient.validateTokenToJson(getCookieAGAIN());

It would be great to:
1) Get the "verified" value via GitkitUser
2) Probably also useful: access to the token value from GitkitClient.getToken()

best regards - Robert

**Comment by dereksalama** [comment]
We should definitely be exposing the "verified" value as part of the user object.

However I don't think it makes sense to have the client return a user's ID Token, since the client could be validating multiple users.

**Comment by robert4os** [comment]
Would be obsolete with pull request https://github.com/google/identity-toolkit-java-client/pull/37
